# Changelog

# ⚠⚠ Please follow the format provided ⚠⚠
#  - name: version number
#    changes:
#      - title: Title of changes
#        categories: [CHANGED AREA]
#        authors: [YourName]


releases:
  - name: 1.6.3
    changes:
    - title: Fix Stuck on Install when not finding UserCfg.opt in MSFS Base Path
      categories: [ Core ]
      authors: [Revyn]
  - name: 1.6.2
    changes:
    - title: Fix Parsing of EXE.xml
      categories: [ Core ]
      authors: [Liz3]
  - name: 1.6.0
    changes:
      - title: Add Feature Auto-Start with MSFS for supported Add-Ons
        categories: [ Core ]
        authors: [Liz3]
      - title: Add MSFS Base Path Option to General Settings
        categories: [ Core ]
        authors: [Revyn112]
      - title: Fix Install Progress Above 100%
        categories: [ UI ]
        authors: [Liz3]
      - title: Fix Installer freeze when external addon could not be found
        categories: [ Core ]
        authors: [Revyn112]
  - name: 1.5.3
    changes:
      - title: Added reload-button to developer configuration
        categories: [ Core ]
      - title: Reset-to-default button for developer configuration
        categories: [ Core ]
      - title: fix move people to new installer config url
        categories: [ Core ]
      - title: update default app window size
        categories: [ Core ]
  - name: 1.5.2
    changes:
    - title: Fix issue with parsing of incorrect manifest.json of 3rd party addons
      categories: [ CORE ]
  - name: 1.5.1
    changes:
    - title: Fix Taskbar Issue with FBW Installer
      categories: [ CORE ]
  - name: 1.5.0
    changes:
      - title: Update UI
        categories: [ UI ]
      - title: Rework External Addons detection
        categories: [ Core ]
      - title: Update Core Code
        categories: [ Core ]
  - name: 1.4.9
    changes:
      - title: Update dependencies
        categories: [ Core ]
  - name: 1.4.7
    changes:
      - title: Disable caching for fetching release configuration 
        categories: [ Core ]
  - name: 1.4.6
    changes:
      - title: Update api-client
        categories: [ Core ]
  - name: 1.4.5
    changes:
      - title: Removes 'v' prefix from Version Numbers
        categories: [ Core ]
  - name: 1.4.4
    changes:
      - title: Add an Option to set a MSFS Base Directory for better dependency checks with Horizon Simulation Addons
        categories: [ Core ]
  - name: 1.4.0
    changes:
      - title: Change Discord Support Url
        categories: [ Core ]
        authors: [ Revyn112 ]
      - title: Add Dependency Check for Steam and OneStore
        categories: [ Core ]
        authors: [ Revyn112 ]
      - title: Update Packages and fixes minor bugs
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.6
    changes:
      - title: Change GitHub Release Type for Pre-Release Builds
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.5
    changes:
      - title: Remove GitHub Issue Button
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.4
    changes:
      - title: Add GitHub Release Type for Staging Builds
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.3
    changes:
      - title: Add Scrollbar to Addon List
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.3.2
    changes:
      - title: Fixes CDN
        categories: [ Infrastructure ]
        authors: [ Revyn112 ]
  - name: 1.3.0
    changes:
      - title: Updated to latest FBW Installer Code
        categories: [ Core ]
        authors: [ Revyn112 ]
      - title: Added local assets
        categories: [ Core ]
        authors: [ Revyn112 ]
      - title: Added GitHub Actions
        categories: [ Logic ]
        authors: [ Revyn112 ]
  - name: 1.2.0
    changes:
      - title: Updated to latest FBW Installer Code
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.1.0
    changes:
      - title: Updated to latest FBW Installer Code
        categories: [ Core ]
        authors: [ Revyn112 ]
  - name: 1.0.0
    changes:
      - title: Initial Release
        authors: [ Revyn112 ]